services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    env_file:
      - .env
    depends_on:
      - app_db

  app_db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root #tochange
      MYSQL_DATABASE: bankiut
      MYSQL_USER: app
      MYSQL_PASSWORD: app #tochange
    ports:
      - "3308:3306"
    expose:
      - '3306'
    volumes:
      - app_db:/var/lib/mysql
      - ./script/dumpSQL.sql:/docker-entrypoint-initdb.d/dumpSQL.sql
#      - ./script/dumpSQL_JUnitTest.sql:/docker-entrypoint-initdb.d/dumpSQL_JUnitTest.sql

  sonarqube:
    image: sonarqube:8.9.10-community
    depends_on:
      - sonar_db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonar_db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar #tochange
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    ports:
      - "9000:9000"
    profiles:
      - sonar

  sonar_db:
    image: postgres:12
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar #tochange
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
    profiles:
      - sonar

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  postgresql:
  postgresql_data:
  app_db:
