name: Java CI with SonarCloud

on:
  push:
    branches:
      - main
      - test
  pull_request:
    branches:
      - main
      - test

jobs:
  build:
    name: Build and Analyze
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: bankiuttest
          MYSQL_USER: myuser
          MYSQL_PASSWORD: mypassword
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -u myuser -pmypassword"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for SonarCloud analysis

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: maven

      - name: Wait for MySQL to Be Ready
        run: sleep 20  # Ensure MySQL has time to start

      - name: Load Seed Data into MySQL
        run: |
          sudo apt-get install -y mysql-client
          mysql -h 127.0.0.1 -u myuser -pmypassword bankiuttest < script/dumpSQL_JUnitTest.sql

      - name: Build and Run Tests
        run: mvn clean verify

      - name: Run SonarCloud Analysis
        run: mvn sonar:sonar -Dsonar.projectKey=your_project_key -Dsonar.organization=your_org_name
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
