name: Java CI with SonarCloud

on:
  push:
    branches:
      - main
      - test
  pull_request:
    branches:
      - main
      - test

jobs:
  build:
    name: Build and Analyze
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for SonarCloud analysis

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11"
          cache: maven

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Start MySQL Database with Docker Compose
        run: |
          docker-compose -f docker-compose.yml -f docker-compose.override.yml up -d
          sleep 15  # Ensure MySQL has time to start

      - name: Check Running Containers
        run: docker ps  # Debugging step to ensure MySQL is running

      - name: Build and Run Tests
        run: mvn clean verify

      - name: Run SonarCloud Analysis
        run: mvn sonar:sonar -Dsonar.projectKey=your_project_key -Dsonar.organization=your_org_name
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Shutdown Database
        run: docker-compose down
